version: "3.7"

services:
    db:
        build: postgres_db
        #ports:
        #  - 5432:5432
        healthcheck:
          test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "postgres" ]
          timeout: 45s
          interval: 10s
          retries: 10
    
    web:
        build: frontend
        ports:
          - 80:80
        depends_on:
          - api

    api:
        build: backend
        environment:
          - PORT=80
          - DB_HOST=db
        #ports:
        #  - 8000:80
        depends_on:
          db:
            condition: service_healthy
    